services:
    app:
        build:
            context: .
            dockerfile_inline: |
                FROM php:8.4-apache
                COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
                RUN apt-get update && apt-get install -y \
                    libpng-dev \
                    libonig-dev \
                    libxml2-dev \
                    zip \
                    unzip \
                    && rm -rf /var/lib/apt/lists/*
                RUN docker-php-ext-install pdo pdo_mysql
                RUN a2enmod rewrite
                ENV APACHE_DOCUMENT_ROOT /var/www/html/public
                RUN sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
                WORKDIR /var/www/html
        container_name: monitor_app
        ports:
            - "8080:80" 
        volumes:
            - .:/var/www/html 
        command: sh -c "composer install --no-interaction && apache2-foreground"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql_db
            - DB_PORT=3306
            - DB_DATABASE=price_monitor
            - DB_USERNAME=sail
            - DB_PASSWORD=123
        depends_on:
            - mysql_db
        networks:
            - price-network

    mysql_db:
        image: mysql:8.0
        container_name: monitor_db
        ports:
            - "33066:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=price_monitor
            - MYSQL_USER=sail
            - MYSQL_PASSWORD=123
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - price-network

networks:
    price-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local